supermarket:
  standard_columns:
    - local_brand_name
    - global_brand_name
    - local_supplier_desc
    - global_supplier_desc
  rules:
    - duplicate_row
    - duplicate_key
    - barcode_length
    - date_format
  
movie:
  standard_columns:
  rules:
    - duplicate_row
    - duplicate_key
    - date_format
